In [1]:
! pip install --upgrade terality

Collecting terality
  Downloading terality-0.14.12-py3-none-any.whl (145 kB)
Requirement already satisfied, skipping upgrade: protobuf<4.0.0,>=3.9.1 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from terality) (3.15.6)
Collecting boto3>=1.16.28
  Downloading boto3-1.21.29-py3-none-any.whl (132 kB)
Collecting pydantic<2.0.0,>=1.7.3
  Downloading pydantic-1.9.0-cp37-cp37m-win_amd64.whl (2.0 MB)
Collecting tqdm<5.0.0,>=4.45.0
  Downloading tqdm-4.63.1-py2.py3-none-any.whl (76 kB)
Requirement already satisfied, skipping upgrade: click<9,>=3.2 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from terality) (7.1.2)
Collecting pyarrow<7.0.0,>=6.0.0
  Downloading pyarrow-6.0.1-cp37-cp37m-win_amd64.whl (15.4 MB)
Collecting sentry-sdk<2.0.0,>=1.3.0
  Downloading sentry_sdk-1.5.8-py2.py3-none-any.whl (144 kB)
Requirement already satisfied, skipping upgrade: pandas<2.0.0,>=1.0.0 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from terality) (1.2.4)
Requirement already satisfied, skipping upgrade: importlib_metadata<5,>=3.0; python_version < "3.8" in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from terality) (4.11.3)
Collecting requests<3.0.0,>=2.23.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied, skipping upgrade: numpy<2.0,>=1.18 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from terality) (1.21.5)
Requirement already satisfied, skipping upgrade: six>=1.9 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from protobuf<4.0.0,>=3.9.1->terality) (1.14.0)
Collecting botocore<1.25.0,>=1.24.29
  Downloading botocore-1.24.29-py3-none-any.whl (8.6 MB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.2-py3-none-any.whl (79 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.0-py3-none-any.whl (23 kB)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4.3 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from pydantic<2.0.0,>=1.7.3->terality) (3.7.4.3)
Requirement already satisfied, skipping upgrade: colorama; platform_system == "Windows" in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from tqdm<5.0.0,>=4.45.0->terality) (0.4.4)
Requirement already satisfied, skipping upgrade: urllib3>=1.10.0 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from sentry-sdk<2.0.0,>=1.3.0->terality) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from sentry-sdk<2.0.0,>=1.3.0->terality) (2020.12.5)
Requirement already satisfied, skipping upgrade: pytz>=2017.3 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from pandas<2.0.0,>=1.0.0->terality) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from pandas<2.0.0,>=1.0.0->terality) (2.8.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from importlib_metadata<5,>=3.0; python_version < "3.8"->terality) (2.2.0)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5; python_version >= "3" in c:\users\ketulp\appdata\local\r-miniconda\lib\site-packages (from requests<3.0.0,>=2.23.0->terality) (2.8)
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Installing collected packages: jmespath, botocore, s3transfer, boto3, pydantic, tqdm, pyarrow, sentry-sdk, charset-normalizer, requests, terality
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.42.1
    Uninstalling tqdm-4.42.1:
      Successfully uninstalled tqdm-4.42.1
  Attempting uninstall: requests
    Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0
Successfully installed boto3-1.21.29 botocore-1.24.29 charset-normalizer-2.0.12 jmespath-1.0.0 pyarrow-6.0.1 pydantic-1.9.0 requests-2.27.1 s3transfer-0.5.2 sentry-sdk-1.5.8 terality-0.14.12 tqdm-4.63.1

ERROR: conda 4.10.0 requires ruamel_yaml_conda>=0.11.14, which is not installed.
ERROR: pycaret 2.3.0 has requirement numpy==1.19.5, but you'll have numpy 1.21.5 which is incompatible.
ERROR: pycaret 2.3.0 has requirement scikit-learn==0.23.2, but you'll have scikit-learn 0.24.1 which is incompatible.
ERROR: pycaret 2.3.0 has requirement scipy<=1.5.4, but you'll have scipy 1.6.2 which is incompatible.

In [3]:
import terality as te
te.configure(
    email="ksboghara@gmail.com",
    api_key="tla_Kiv78aqh6CtxvJ0wOP9lbG9CCONdhfWD3cXglZ1DUDgsGUBnhGEfgKuUDE6Z02R9Wa"
)

WARNING:terality:A Terality configuration file is already present at C:\Users\Ketulp\.terality\config.json.
WARNING:terality:A Terality credentials file is already present at C:\Users\Ketulp\.terality\credentials.json.
INFO:terality:Terality account successfully configured on this system.

In [12]:
import terality as te

# You can now process your data with Terality:
df = te.read_csv("india-covid-data.csv")

india-covid-data.csv: 100%|███████████████████████████████████████████████████████| 1.92k/1.92k [00:01<00:00, 1.87kB/s]

In [13]:
df

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio (%),Discharge Ratio (%),Death Ratio (%)
0,Andaman and Nicobar,7546,5,7412,129,0.07,98.22,1.71
1,Andhra Pradesh,1983721,19549,1950623,13549,0.99,98.33,0.68
2,Arunachal Pradesh,50372,2606,47520,246,5.17,94.34,0.49
3,Assam,575220,11096,558720,5404,1.93,97.13,0.94
4,Bihar,725235,286,715303,9646,0.04,98.63,1.33
5,Chandigarh,61984,27,61146,811,0.04,98.65,1.31
6,Chhattisgarh,1003244,1700,988004,13540,0.17,98.48,1.35
7,Dadra and Nagar Haveli and Daman and Diu,10653,6,10643,4,0.06,99.91,0.04
8,Delhi,1436800,498,1411235,25067,0.03,98.22,1.74
9,Goa,171944,896,167884,3164,0.52,97.64,1.84
10,Gujarat,825064,209,814778,10077,0.03,98.75,1.22
11,Haryana,770091,672,759769,9650,0.09,98.66,1.25
12,Himachal Pradesh,208197,2086,202576,3535,1.00,97.30,1.70
13,Jammu and Kashmir,322658,1311,316957,4390,0.41,98.23,1.36
14,Jharkhand,347406,202,342074,5130,0.06,98.47,1.48
15,Karnataka,2919711,23342,2859552,36817,0.80,97.94,1.26
16,Kerala,3565574,170031,3377691,17852,4.77,94.73,0.50
17,Ladakh,20400,72,20121,207,0.35,98.63,1.01
18,Lakshadweep,10249,54,10145,50,0.53,98.99,0.49
19,Madhya Pradesh,791970,149,781307,10514,0.02,98.65,1.33
20,Maharashtra,6357833,71813,6151956,134064,1.13,96.76,2.11
21,Manipur,104791,7006,96128,1657,6.69,91.73,1.58
22,Meghalaya,69358,4734,63450,1174,6.83,91.48,1.69
23,Mizoram,45457,12434,32854,169,27.35,72.27,0.37
24,Nagaland,28709,1397,26727,585,4.87,93.10,2.04
25,Odisha,987956,10064,971391,6501,1.02,98.32,0.66
26,Puducherry,121665,834,119031,1800,0.69,97.84,1.48
27,Punjab,599514,441,582753,16320,0.07,97.20,2.72
28,Rajasthan,953840,216,944670,8954,0.02,99.04,0.94
29,Sikkim,27908,2731,24822,355,9.79,88.94,1.27
30,Tamil Nadu,2577237,20427,2522470,34340,0.79,97.87,1.33
31,Telengana,649859,8242,637789,3828,1.27,98.14,0.59
32,Tripura,80416,2044,77601,771,2.54,96.50,0.96
33,Uttar Pradesh,1708793,570,1685449,22774,0.03,98.63,1.33
34,Uttarakhand,342423,446,334609,7368,0.13,97.72,2.15
35,West Bengal,1534360,10312,1505808,18240,0.67,98.14,1.19

In [14]:
import pandas as pd
df_pd = pd.read_csv("india-covid-data.csv")

In [15]:
df_pd

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio (%),Discharge Ratio (%),Death Ratio (%)
0,Andaman and Nicobar,7546,5,7412,129,0.07,98.22,1.71
1,Andhra Pradesh,1983721,19549,1950623,13549,0.99,98.33,0.68
2,Arunachal Pradesh,50372,2606,47520,246,5.17,94.34,0.49
3,Assam,575220,11096,558720,5404,1.93,97.13,0.94
4,Bihar,725235,286,715303,9646,0.04,98.63,1.33
5,Chandigarh,61984,27,61146,811,0.04,98.65,1.31
6,Chhattisgarh,1003244,1700,988004,13540,0.17,98.48,1.35
7,Dadra and Nagar Haveli and Daman and Diu,10653,6,10643,4,0.06,99.91,0.04
8,Delhi,1436800,498,1411235,25067,0.03,98.22,1.74
9,Goa,171944,896,167884,3164,0.52,97.64,1.84
10,Gujarat,825064,209,814778,10077,0.03,98.75,1.22
11,Haryana,770091,672,759769,9650,0.09,98.66,1.25
12,Himachal Pradesh,208197,2086,202576,3535,1.00,97.30,1.70
13,Jammu and Kashmir,322658,1311,316957,4390,0.41,98.23,1.36
14,Jharkhand,347406,202,342074,5130,0.06,98.47,1.48
15,Karnataka,2919711,23342,2859552,36817,0.80,97.94,1.26
16,Kerala,3565574,170031,3377691,17852,4.77,94.73,0.50
17,Ladakh,20400,72,20121,207,0.35,98.63,1.01
18,Lakshadweep,10249,54,10145,50,0.53,98.99,0.49
19,Madhya Pradesh,791970,149,781307,10514,0.02,98.65,1.33
20,Maharashtra,6357833,71813,6151956,134064,1.13,96.76,2.11
21,Manipur,104791,7006,96128,1657,6.69,91.73,1.58
22,Meghalaya,69358,4734,63450,1174,6.83,91.48,1.69
23,Mizoram,45457,12434,32854,169,27.35,72.27,0.37
24,Nagaland,28709,1397,26727,585,4.87,93.10,2.04
25,Odisha,987956,10064,971391,6501,1.02,98.32,0.66
26,Puducherry,121665,834,119031,1800,0.69,97.84,1.48
27,Punjab,599514,441,582753,16320,0.07,97.20,2.72
28,Rajasthan,953840,216,944670,8954,0.02,99.04,0.94
29,Sikkim,27908,2731,24822,355,9.79,88.94,1.27
30,Tamil Nadu,2577237,20427,2522470,34340,0.79,97.87,1.33
31,Telengana,649859,8242,637789,3828,1.27,98.14,0.59
32,Tripura,80416,2044,77601,771,2.54,96.50,0.96
33,Uttar Pradesh,1708793,570,1685449,22774,0.03,98.63,1.33
34,Uttarakhand,342423,446,334609,7368,0.13,97.72,2.15
35,West Bengal,1534360,10312,1505808,18240,0.67,98.14,1.19